---
version: "3"

services:
  socket-proxy:
    image: "tecnativa/docker-socket-proxy:latest"
    container_name: "socket-proxy"
    restart: unless-stopped
    privileged: true
    ports:
      - "127.0.0.1:2375:237"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - docker-socket
    environment:
      BUILD: 1
      COMMIT: 1
      CONFIGS: 1
      CONTAINERS: 1
      DISTRIBUTION: 1
      EXEC: 1
      IMAGES: 1
      INFO: 1
      NETWORKS: 1
      NODES: 1
      PLUGINS: 1
      SERVICES: 1
      SESSION: 1
      SWARM: 1
      SYSTEM: 1
      TASKS: 1
      VOLUMES: 1

networks:
  docker-socket:
    name: docker-socket-network
    external: true
