---
version: "3"

services:
  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    restart: unless-stopped
    env_file: .env
    ports:
      - 32400:32400/tcp
      - 32400:32400/udp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    volumes:
      - "${STORAGE_BASE:?err}/plex:/config"
      - "${REPO_BASE:?err}/media/shows:/tv"
      - "${REPO_BASE:?err}/media/movies:/movies"
      - "${REPO_BASE:?err}/media/music:/music"
