---
version: "2.1"
services:
  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    restart: unless-stopped
    env_file: .env
    volumes:
      - "${STORAGE_BASE:?err}/plex:/config"
      - "${REPO_BASE:?err}/media/shows:/tv"
      - "${REPO_BASE:?err}/media/movies:/movies"
      - "${REPO_BASE:?err}/media/music:/music"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.plex.rule=Host(`plex.localdomain`)"
      - "traefik.http.routers.plex.entrypoints=web"
      - "traefik.http.routers.plex.service=plex"
      - "traefik.http.services.plex.loadbalancer.server.port=32400"

networks:
  default:
    name: traefik-network
    external: true
