FROM ghcr.io/gethomepage/homepage:latest
COPY ./config/bookmarks.yaml ./config/bookmarks.yaml
COPY ./config/services.yaml ./config/services.yaml
COPY ./config/settings.yaml ./config/settings.yaml
COPY ./config/widgets.yaml ./config/widgets.yaml
