---
version: "3"

services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    cap_add:
      - NET_ADMIN # Recommended but not required (DHCP needs NET_ADMIN)
    volumes:
      - "/data/virt/docker/pihole/etc-pihole:/etc/pihole"
      - "/data/virt/docker/pihole/etc-dnsmasq.d:/etc/dnsmasq.d"
    environment:
      TZ: 'Europe/London'
      VIRTUAL_HOST: pihole.localdomain
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.entrypoints=web"
      - "traefik.http.routers.pihole.rule=Host(`pihole.localdomain`)"
      - "traefik.http.routers.pihole.service=pihole"
      - "traefik.http.services.pihole.loadBalancer.server.port=80"

networks:
  default:
    name: traefik-network
    external: true
