version: "3"

services:
  nginx-rev-proxy:
    container_name: nginx-rev
    image: nginx:latest
    ports:
      - 80:80
      # - 8080:8080
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
