---
version: "3"

services:
  traefik:
    image: "traefik:v2.8"
    container_name: "traefik"
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    networks:
      - traefik
      - docker-socket
    volumes:
      - ./traefik.yaml:/etc/traefik/traefik.yaml:ro

networks:
  traefik:
    name: traefik-network
    external: true
  docker-socket:
    name: docker-socket-network
    external: true
