---
version: "3"

services:
  web1:
    image: httpd
    container_name: web1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web1.rule=Host(`web1.localdomain`)"
      - "traefik.http.routers.web1.entrypoints=web"

networks:
  default:
    name: traefik-network
    external: true
