---
version: "3"


services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /data/virt/docker/portainer:/data
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.entrypoints=web"
      - "traefik.http.routers.portainer.rule=Host(`portainer.localdomain`)"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
    networks:
      - traefik

networks:
  traefik:
    name: traefik-network
    external: true
